# Generated by Django 2.0.4 on 2018-05-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_done', to='profiles.Profile')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to='profiles.Profile')),
            ],
        ),
    ]
